<!DOCTYPE html>
<html>
<body>

<h1>Raport 1</h1>
<h2> Tiperciuc Stefan(3A5)</h1>

<p>In acest raport voi prezenta jocuri pe care doresc sa il implementez la disciplina Proiectarea Jocurilor, task-ul facut pana in saptamana a 2-a si ce planuiesc sa fac pentru saptamana a 3-a.</p>
<p>Proiectul pe care doresc sa il implementez la disciplina Proiectarea Jocurilor este o implementare 2D in Unity a jocului de societate Takenoko. Acesta este un joc competitive de 2-4 jucatori, in care fiecare jucator incearca, individual, sa obtina cat mai multe puncte prin rezolvarea de misiuni. In fiecare tura, jucatorul are posibilitatea de a facut 2 actiuni ( excluzand anumite conditii speciale) printer care se numara: alegerea unei misiuni noi, extragerea unei parcele de pamant de culoare aleatoare, folosirea Fermierului pentru a creste o bucata de bambus pe o anumita parcela de pamant, a Ursului panda pentru a banca o bucata de bambus sau de a lua o bucata de irigatie. Odata ce un jucator a terminat 7 misiuni, la finalul turei, jucatorul cu cele mai multe puncta castiga.</p>
<p>In cadrul acestui joc, eu voi folosi motorul de Joc Unity pentru a crea o implementare 2D a acestui joc. Intentionez sa implementez toate interactiunile prezente in jocul de baza (mutarea pieselor in mod corect, rezolvarea misiunilor si a turelor jucatorilor etc.) folosind asset-urile originale (cartile de misiune, imaginile pentru panda, fermier, bambus) pe care le voi extrage de pe internet. Dupa aceasta, daca imi permite timpul, dorect sa transpun si in plan 3D aceasta idee si sa aduc reguli noi jocului de baza, asemanator cu un expansion.</p>
<p>In decursul primei saptamani mi-am propus sa ma familiarizez cu interfata motorului de joc Unity, intrucat nu am mai facut nici un joc inainte. Am ales Unity in favoarea altor motoare, intrucat se potriveste cel mai bine pe cerintele jocului ce dorect sa il implementez (2D, nu necesita suport multiplayer major) si foloseste C#, care este mult mai user friendly pentru incepatori decat C++. In prima saptamana am urmarit un tutorial pe Youtube despre cum sa faci un platformer in Unity si l-am si construit de la 0. Astfel, m-am familiarizat putin cu interfata Unity-ului, cu diferitele componente necesare unui platformer, cu crearea de UI simplist, cu Animatorul si cu scrierea de cod in C#. Cu toate ca multe din aceste elemente nu vor fi folosit in proiectul pe care mi l-am propus sa il fac, consider ca experienta pe care am obtinut-o dupa acest tutorial tot imi va usura munca cand incep lucrul la proiect propriu-zis.</p>
<p>Pentru saptamana a 3-a doresc sa implementez scheletul de baza al jocului in Unity. Voi incerca sa implementez grid-ul de baza ce sa in spatele jocului, plasarea de parcele de pamant in acest grid si a diferitor piese ce se afla pe acestea ( bambus, fermier si panda). Consider ca acestea reprezinta cel mai important prim pas al proiectului, intrucat ele stau la baza gameplay-ului si fara el nu pot sa fac restul implementarii.</p>

</body>
</html>